### ISSUE TITLE
OP1080 Selecting "Send me a copy" fails if letter case of sender email does not match that held in Contacts

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-contact-form#17]
When a logged in user uses the Contact Form, there is an option to "Send me a copy".  To prevent mistakes or abuse, the code checks that the email address provided in the "Your email address" field and will only send a copy if this matches the User's email address.  However the current code performs a case-sensitive check so will not send a copy when the email address given only differs in letter case.

Current code:
`// Only send user a copy if they have used their own email address.`
`if (wp_get_current_user()->user_email == $returnEmail) {`

We should probably use strcasecmp:
`// Only send user a copy if they have used their own email address.`
`if (strcasecmp(wp_get_current_user()->user_email, $returnEmail) == 0) {`

It also occurs to me that where the user is logged in we should retrieve their email address so they don't need to type it in to the form and make the "Your email address" field read-only.

**Comment by mike99christie** [comment]
Implemented in version 1.1.2
