### ISSUE TITLE
Message sent message. Offer customsable setting?

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-contact-form#5]
The original release shown the text "Message sent successfully".  I'm not sure why this has been changed to "Message sent to recipient".  I think the original wording is more straightforward.

However, perhaps that message should be customisable?  A u3a may want to say more when a message has been successfully?  Perhaps to add something like "if you have not had a reply in xx days please contact zzz"?

**Comment by mike99christie** [comment]
Defer customised message.
