### ISSUE TITLE
Move u3a contact log so a sub-menu

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-contact-form#6]
To avoid cluttering the dashboard menu, could this be a sub-menu of u3a Settings?

**Comment by mike99christie** [comment]
Is it really cluttered?
Obviously it would be possible to check if the u3a-core plugin admin menu exists and use it if so, but I'd like to ensure the plugin will also work stand-alone, so am not sure the extra complexity is worth it.
